GROQ_API_KEY = "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"

[connections.postgresql]
dialect = "postgresql"
host = "database-1.c1uguiucyb5i.ap-southeast-2.rds.amazonaws.com"
port = "5432"
database = "coba"
username = "postgres"
password = "Postgres001"